### PR TITLE
Add id and email getter

### PR DESCRIPTION
**Pull request by takayukioda**
Add some getter to use in code-main.
@shunjikonishi please review, thanks.

### CODE REVIEW

**Comment by shunjikonishi** [comment]
@da0shi fix me

```
def id = get("id").toLong
```

BTW. 
If API user doesn't have permission, email returns empty string.
Be careful

**Comment by takayukioda** [comment]
> If API user doesn't have permission, email returns empty string.
> Be careful

Thanks. Should I declare with `def email: Option[String]`?

**Comment by shunjikonishi** [comment]
No.
Empty string is different from null.
As long as I verified, email key always exists.
So I think it is better to user 'def email: String'.

**Comment by takayukioda** [comment]
@shunjikonishi please review again thanks.

BTW, it seems that github-hook is not working well. Does something changed during update on github-hook?

**Comment by shunjikonishi** [comment]
Yes, I updated github-api-scala.jar.
I'll investigate later.

**Comment by takayukioda** [comment]
I see :+1:

**Comment by shunjikonishi** [comment]
LGTM

**Pull request merged**
