### PR TITLE
9 update authenticated user

### PR DESCRIPTION
**Pull request by sukeshni**
Just creating a pull request. Will work on the conversion.

### CODE REVIEW

**Comment by shunjikonishi** [comment]
@sukeshni 
FYI: @fanwashere 

## getUser

Maybe you copied getUser method and its test from previous branch.
But it is not necessary.
Because we already merged by #18 
It cause conflict. This pullrequest can't merge automatically.

This time, I'll merge this pullrequest manually.
So, you don't have to fix code about this.

## UserInput#apply

These methods are redundancy.

For example, if you want to change just company field, your methods are not useful.

Scala has named parameter. So, you can construct UserInput like this.

``` scala
val a = UserInput(company=Some("fuga"))
val b = UserInput(name=Some("hoge"), company=Some("fuga"))
```

I think all of UserInput fields are option. 
So, I think we don't need any overloaded apply methods.

## Test

Test for updateAuthenticatedUser is not enough.
And not reusable.

Because once this test run, the name of user is changed and not turn back.
So, if you run this test twice, you can't detect the result is correct or not.

I'll rewrite test after merging this pullrequest.
So now, you don't have to fix test.

@sukeshni fix me about UserInput#apply.

**Comment by shunjikonishi** [comment]
@sukeshni 
What is your last commit?

**Comment by sukeshni** [comment]
I tried to create a wrapper, (by referring to Fan's soln of implicit).
Also this can works without import.
So we will use Opt[String] instead of Option[String] and the wrapper will take care of the internal conversions.

**Comment by shunjikonishi** [comment]
No.
I think this is one of reinventing the wheel.
Scala already has Option. Using your Opt instead of Option is very confusing for Scala developer.
We have to respect the custom of Scala developers.
So, we should use Option.

And I have other two questions.
- Why you remove fields from User class? (name, blog, etc...)
- Why you remove fields from UserInput class? (email, blog, etc...)

I think these were correct implementation.

I think previous commit was enough for this task.

https://github.com/code-check/github-api-scala/commit/dd87cd485b3d2c4958c106be34838e4d40bbd635

Please revert it.

**Comment by shunjikonishi** [comment]
@fanwashere @sukeshni @da0shi 

implicit def is very powerful and useful feature.
But sometimes this is very confusing.
Don't use too much.

I think, at the begining of learning Scala, it is better to just use.
At least we don't need to define implicit def in developing github-api-scala.

**Comment by takayukioda** [comment]
+1

**Comment by shunjikonishi** [comment]
@sukeshni 
When you finish implementation, please write mention with the word 'review'.
Like this.

@shunjikonishi review

So, automatically 'Review me!' label is added and assign to reviewer.

**Comment by sukeshni** [comment]
@shunjikonishi review

**Comment by shunjikonishi** [comment]
@sukeshni review me
FYI @fanwashere 

I added some refactoring see

https://github.com/code-check/github-api-scala/commit/7a4fb82cac01967d73950039ceba8d1de250436c

## Invalid data type
- hireable is Boolean
- bio is Option[String]

See https://developer.github.com/v3/users/#get-a-single-user

bio field is not exist, if it is not set.
So we have to handle this field as Option.

Unfortunately GitHub API documentation doesn't tell us to each fields are always exist or not.
So we have to verify the response to decide each field is Option or not.

## Turn back user information to original values.

Your test rewrite username.
It is very inconvenience.

So you have to turn back them to original values.

## Test for all fields

You have to test all fields of User/UserInput.
Because
- There might be typo in field name.
- The field might not exists

In fact, I could be aware that bio field is an option by writing test.

When you add new field to some model class, you have to write its test.

**Comment by sukeshni** [comment]
@shunjikonishi 
Million thanks for the explanation.
LGTM

**Pull request merged**
