### PR TITLE
3 issue api

### PR DESCRIPTION
**Pull request by fanwashere**

### CODE REVIEW

**Comment by fanwashere** [comment]
I'm stuck on making the issue specs compatible with the milestone specs.

Issue specs require 2 milestones in the user's own test repo and the organization's test repo. These milestones are constantly being deleted by the Milestone spec. I tried using BeforeAndAfter in Issue spec but it is not behaving as expected.

Ideally, the following should happen:
1. Issue spec creates the 2x2 required milestones.
2. Issue spec runs and ends.
3. Milestone spec removes all milestones.
4. Milestone spec runs and ends.

**Comment by shunjikonishi** [comment]
What's the problem?

I checked out this branch, but your code doesn't mixin BeforeAndAfter.
I think you can do avobe things with BeforeAndAfter.

**Comment by fanwashere** [comment]
I added the commit with BeforeAndAfter. It gives either fails half the tests or aborts the suite.

**Comment by fanwashere** [comment]
@shunjikonishi review me.

There is definitely some sort of concurrency issue with the tests, so I created a second test repo (test-repo2) so that it will never conflict with the other specs. One test in OrganizationOpSpec had to be changed to accommodate the second repo.

**Comment by shunjikonishi** [comment]
Initially, IssueOpSpec failed 5 tests with my local environment,
Next, I could run all test without error by following command

``` bash
sbt test -Duser.timezone=GMT
```

So, I guess this is timezone problem. #45  
Maybe you could reproduce my error with following command.

```
sbt test -Duser.timezone=Asia/Tokyo
```

I think this is another problem.
So, I give you LGTM!

LGTM

**Comment by fanwashere** [comment]
@shunjikonishi review me.

The error is most likely produced by the following line:

``` scala
var nTime: DateTime = DateTime.now()
```

Which I use the get the current time so I can compare with the created_at and updated_at time. I added a line to convert your local time into UTC, as I assume Github is on UTC time. 

``` scala
var nTime: DateTime = DateTime.now().toDateTime(DateTimeZone.UTC)
```

This should solve the error. Please use commit 96088ef to test this.

Also, I noticed the master I used for the base of this branch is outdated and in AbstractJson, the date() function was changed to getDate() recently. The last commit (a8d92d4) uses the new getDate() function. Don't test with this as the branch is still using the date() function.

**Comment by shunjikonishi** [comment]
@fanwashere fix me

To solve conflict,  try following step

``` bash
$ git checkout master
$ git pull origin master
$ git checkout 3-issueAPI
$ git rebase master
(Maybe conflict happen, so you have to fix them with your editor.)
$ git rebase --continue
$ git push -f origin 3-issueAPI
```

The points are
- use 'rebase' to merge master to branch
- use '-f' option in last git push

This is basic way to merge master to branch.

FYI @sukeshni

**Comment by fanwashere** [comment]
@shunjikonishi Thanks for the advice, this will be useful in the future as I constantly forget to rebase before I make a branch.

@sukeshni review me.

**Comment by sukeshni** [comment]
LGTM

**Pull request merged**
