### PR TITLE
Publish to Sonatype

### PR DESCRIPTION
**Pull request by ashawley**
It would be nice to have this published so the library could be used easier in projects.

  - Add meta information
  - Add POM bits
  - Enable sbt-pgp plugin
  - Add instructions to README

Directions on publishing:

http://www.scala-sbt.org/0.13/docs/Using-Sonatype.html

### CODE REVIEW

**Comment by ashawley** [comment]
@shunjikonishi Would you want to make a releases of this library to Sonatype?

Right now, I have 6 other open pull requests.  I don't have any plans to make more pull requests, so we wouldn't have to make any more releases after that.

**Comment by shunjikonishi** [comment]
@ashawley Sorry for late response. I have free time tomorrow. I'll check them tomorrow.

**Comment by shunjikonishi** [comment]
@ashawley 
I almost check and merged your PR except StatusAPI. Please check it.

**Comment by ashawley** [comment]
ありがとう！



Thanks for merging all those PRs.

I have fixed the PR for StatusAPI.  It should be good.

**Pull request merged**
