### PR TITLE
[WIP] getUser

### PR DESCRIPTION
**Pull request by shunjikonishi**
Implement getUser method and test
- [x] API
- [x] test

### CODE REVIEW

**Comment by shunjikonishi** [comment]
#9 Implement getUser

@fanwashere  @sukeshni please review

**Comment by shunjikonishi** [comment]
@sukeshni 
Please trace this code for excersice.
Implement it by yourself.

**Comment by sukeshni** [comment]
@shunjikonishi Review me!

**Comment by shunjikonishi** [comment]
@sukeshni 
This pullrequest includes only my commits.
I think your implementation is in getuser-skesuni branch.
Please make pullrequest with that branch.
(Though it is not necessary, I ask you for your practice.)

**Comment by sukeshni** [comment]
@shunjikonishi made pull request. Thank you for making me learn things :)

**Comment by shunjikonishi** [comment]
@fanwashere 
@sukeshni 

You two finished implementing this.
So, I'll merge it.

**Pull request merged**
