### PR TITLE
[WIP]

### PR DESCRIPTION
**Pull request by sukeshni**

### CODE REVIEW

**Comment by sukeshni** [comment]
@shunjikonishi Review me

**Comment by shunjikonishi** [comment]
@sukeshni fix me

Not good.

The API definition of getAllUsers is here.

https://developer.github.com/v3/users/#get-all-users

Its endpoint is '/users'.
'since' is its parameter.

So, correct implementation is like this.

``` scala
val path = if (since == 0) "/users" else s"/users?since=$since"
exec("GET", path).map(...)
```

Maybe this implementation doesn't work.
You have to verify it works before asking review.
It can achieve by making test.

**Comment by sukeshni** [comment]
@shunjikonishi Review me

**Comment by shunjikonishi** [comment]
@sukeshni fix me

## Use showResponse instead of println

https://github.com/code-check/github-api-scala/blob/master/src/test/scala/Constants.scala#L25-L29
replace println -> showResponse

## About since test

Maybe following is better.

``` scala
      val res = Await.result(api.getAllUsers(userOpGet.id - 1), TIMEOUT)
      assert((res{0}.id).toLong == userOpGet.id)
```

Because the user might be removed.

**Comment by sukeshni** [comment]
@shunjikonishi fixed println -> showResponse

About since test
I think it won't make a difference.
Here there will be a possibility that userId (userOpGet.id - 1) is not present to fetch records.
Help me with which case to write.

**Comment by shunjikonishi** [comment]
@sukeshni 

I guess, if specified userId doesn't exist, it will work.

Because I guess server side code might be like this.

``` sql
SELECT ... FROM users where id > :since
```

If so, my code will always succeed, but your code might fail.

**Comment by sukeshni** [comment]
@shunjikonishi Oh alright, got it, will do it asap, thanks.

**Comment by sukeshni** [comment]
@shunjikonishi Review me.

**Comment by shunjikonishi** [comment]
LGTM

**Pull request merged**
