### PR TITLE
[WIP] #11 - organizationAPI

### PR DESCRIPTION
**Pull request by fanwashere**

### CODE REVIEW

**Comment by fanwashere** [comment]
@shunjikonishi review me.

**Comment by shunjikonishi** [comment]
@fanwashere 

When you ask someone code review, please write short summary.

You added following fields in OrganizationDetail.

``` scala
  def followers = get("followers").toInt
  def following = get("following").toInt
  def html_url = get("html_url")
  def created_at = date("created_at")
  def updated_at = date("updated_at")
  def `type` = get("type")
```

But not tested.
You have to call these methods at least once in test.
There might be some typo or other bug.

And about OrganizationOp#updateOrganization.
Your returns 

Future[Option[OrganizationDetail]]

But I think this option is not necessary.
Because when API user calls this method, he/she should always specify correct repository.
Maybe wrong repository name is a bug of API user.

So this Option is redundancy.

**Comment by shunjikonishi** [comment]
@fanwashere fix me

**Comment by fanwashere** [comment]
@shunjikonishi review me. 

Sorry for my lack of summary. I usually write a detailed summary of change with every commit, if that helps. 

I added the tests for the mentioned fields, and changed the return type of updateOrganization as you suggested. I think I now understand when to leave it to the user to make sure they enter the right info.

**Comment by shunjikonishi** [comment]
@fanwashere 
I see.
I usually write just one line in commit comment.
So, I didn't notice your commit comment.

However, still I think it is better to write summary in PullRequest.
Because to see commit comment, I have to click some link.

LGTM

**Pull request merged**
