### PR TITLE
Improve PullRequest and IssueEvent with tests

### PR DESCRIPTION
**Pull request by ashawley**
I used the example JSON from https://developer.github.com/v3/activity/events/types/ to improve the Pull Request event type.  I followed the philosophy for models of **"We don't aim to define all fields of JSON.  We just define the fields we need."** as defined in the `README.md`.

I was primarily interested in getting the `pull_request.head.label` from a `PullRequestEvent`.  This patch makes it work.

Thank you for this library!

### CODE REVIEW

**Comment by shunjikonishi** [comment]
Will check in weekend

**Comment by ashawley** [comment]
I had a lot of unnecessary duplication in the GitHubEventSpec.  I've reduced the number of times the pattern match was happening, and just did more nesting where I could.

So this:

```
    it("should yield IssueEvent") {
      event shouldBe a [IssueEvent]
    }
    it("should have a name") {
      inside(event) {
        case e @ IssueEvent(name, _) =>
          assert(name === "issue")
      }
    }
    it("should have an action") {
      inside(event) {
        case e @ IssueEvent(_, _) =>
          assert(e.action === models.IssueAction.opened)
      }
    }
```

will become

```
    it("should yield IssueEvent") {
      event shouldBe a [IssueEvent]
    }
    describe("IssueEvent") {
      inside(event) {
        case e @ IssueEvent(name, _) =>
          it("should have a name") {
            assert(name === "issue")
          }
          it("should have an action") {
            assert(e.action === models.IssueAction.opened)
          }
      }
    }
```

**Comment by shunjikonishi** [comment]
@ashawley fix me

I think the values of IssueAction are not enough.

I've checked my application logs for this event.
And found some of them has the value `"action": "edited"`.

I couldn't find list of actions in [GitHub API document](https://developer.github.com/v3/).

If we couldn't know list of action values, I think this implementation is risky.
Because when unknown action is appeared in `action` field, it will be RuntimeException.

**Comment by ashawley** [comment]
@shunjikonishi You are right about "edited":

https://developer.github.com/v3/activity/events/types/#issuesevent

**Comment by ashawley** [comment]
@shunjikonishi I've added an `edited` action for pull requests and issues.  I had copied the actions from pull request.  They are both fixed, now.

I fixed a bug for the `repo` for a pull request's `base` and `head`.

**Pull request merged**
