### PR TITLE
Update README.md with new environment variables for test

### PR DESCRIPTION
**Pull request by ashawley**
Otherwise, the Constants mixin fails to initialize test 

```
[info] DeferredAbortedSuite:
[info] Exception encountered when attempting to run a suite with class name: org.scalatest.DeferredAbortedSuite *** ABORTED ***
[info]   java.lang.NoClassDefFoundError: Could not initialize class Constants$
[info]   at Constants$class.$init$(Constants.scala:14)
[info]   at IssueOpSpec.<init>(IssueOpSpec.scala:20)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
[info]   at java.lang.Class.newInstance(Class.java:442)
[info]   at org.scalatest.tools.Framework$ScalaTestTask.execute(Framework.scala:468)
[info]   at sbt.TestRunner.runTest$1(TestFramework.scala:76)
[info]   at sbt.TestRunner.run(TestFramework.scala:85)
[info]   ...
```

### CODE REVIEW

**Comment by ashawley** [comment]
Ah, didn't notice the file at `src/test/scala/README.md`.  Merge with the file at the root directory?

**Comment by shunjikonishi** [comment]
Hi, Thank you for PR.
Tests of this repo depends on GitHub user/repo status.
So, currently some test might not work.

**Comment by shunjikonishi** [comment]
`src/test/scala/README.md` is same as `[ROOT]/test.md`.

**Comment by ashawley** [comment]
I was able to run PullRequestOpSpec and create shunjikonishi/test-repo#53, so that was good enough for what I was working on.

**Comment by ashawley** [comment]
Only 20 tests out of 75 fail, probably because I'm not in the celestialbeings organization.

```
[info] Run completed in 11 seconds, 199 milliseconds.
[info] Total number of tests run: 75
[info] Suites: completed 9, aborted 2
[info] Tests: succeeded 55, failed 20, canceled 0, ignored 0, pending 0
[info] *** 2 SUITES ABORTED ***
[info] *** 20 TESTS FAILED ***
[error] Failed tests:
[error]     LabelOpSpec
[error]     UserOpSpec
[error]     WebhookOpSpec
[error]     CollaboratorOpSpec
[error] Error during tests:
[error]     MilestoneOpSpec
[error]     OrganizationOpSpec
[error]     IssueOpSpec
[error] (test:test) sbt.TestsFailedException: Tests unsuccessful
[error] Total time: 15 s, completed Oct 14, 2016 8:36:45 AM
```

**Pull request merged**
