### PR TITLE
Add status API support resolves #68

### LINKED ISSUE #68: Status API
- Create*
- List
- Get

https://developer.github.com/v3/repos/statuses/

https://github.com/blog/1227-commit-status-api

\* Create is the important one for me

### PR DESCRIPTION
**Pull request by ashawley**
Can create, list and get combined status of a commit (or a reference for the latter two).

I've left namespaces commented out in advance of getting #66 merged.  Happy to fixup this pull request if you merge that one first.

### CODE REVIEW

**Comment by shunjikonishi** [comment]
@ashawley 
Test doesn't work. 

The commit `364ca6d43b5aea6a82aab5cd576eb9ccad6da537` doesn't exist in repo `shunjikonishi/test-repo`.

How to test it?

**Comment by ashawley** [comment]
Sorry, it should test with celestialbeings/test-repo

I will rebase and commit fix

**Comment by shunjikonishi** [comment]
@ashawley 
createAPI still doesn't work for me.

APIKEY needs some special permission?

```
[info] - should be pending *** FAILED ***
[info]   codecheck.github.exceptions.NotFoundException: {
[info]   "message" : "Not Found",
[info]   "documentation_url" : "https://developer.github.com/v3"
[info] }
[info]   at codecheck.github.api.GitHubAPI$$anon$1.onCompleted(GitHubAPI.scala:76)
[info]   at codecheck.github.transport.asynchttp20.AsyncHttp20Request$$anon$1.onCompleted(AsyncHttp20Transport.scala:43)
[info]   at codecheck.github.transport.asynchttp20.AsyncHttp20Request$$anon$1.onCompleted(AsyncHttp20Transport.scala:41)
[info]   at org.asynchttpclient.AsyncCompletionHandler.onCompleted(AsyncCompletionHandler.java:64)
[info]   at org.asynchttpclient.netty.NettyResponseFuture.getContent(NettyResponseFuture.java:188)
[info]   at org.asynchttpclient.netty.NettyResponseFuture.done(NettyResponseFuture.java:223)
[info]   at org.asynchttpclient.netty.handler.HttpHandler.finishUpdate(HttpHandler.java:58)
[info]   at org.asynchttpclient.netty.handler.HttpHandler.handleChunk(HttpHandler.java:159)
[info]   at org.asynchttpclient.netty.handler.HttpHandler.handleRead(HttpHandler.java:187)
[info]   at org.asynchttpclient.netty.handler.AsyncHttpClientHandler.channelRead(AsyncHttpClientHandler.java:83)
[info]   ...
```

**Comment by ashawley** [comment]
Yes, I guess it does need permissions.  According to https://developer.github.com/v3/repos/statuses/

> Note that the `repo:status` OAuth scope grants targeted access to Statuses **without** also granting access to repository code, while the `repo` scope grants permission to code as well as statuses.
I guess we should just all have the same commit in our test-repo?

https://github.com/celestialbeings/test-repo/tree/364ca6d43b5aea6a82aab5cd576eb9ccad6da537

It's just missing from yours:

https://github.com/shunjikonishi/test-repo/tree/364ca6d43b5aea6a82aab5cd576eb9ccad6da537

May be you could just add it as a branch to your test-repo?

```
$ git clone git@github.com:shunjikonishi/test-repo.git
$ cd test-repo
$ git remote add upstream git@github.com:celestialbeings/test-repo.git
$ git fetch upstream
$ git checkout -b celestialbeings upstream/master
$ git push origin celestialbeings
```

**Comment by ashawley** [comment]
I've changed the test so that it is against userRepo, so it should have the right permission.

**Comment by shunjikonishi** [comment]
worked. I've misunderstood StatusAPI. Thanks

LGTM

**Pull request merged**
